---
title: "Visualization"
author: "yz5248"
date: "2025-09-25"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(ggplot2)
library(patchwork)
library(p8105.datasets)
```

import the weather data
```{r}
data("weather_df")
```

making our first plot :-)
```{r}
ggplot(data = weather_df, mapping = aes(x = tmin, y = tmax)) + 
  geom_point()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

```{r}
ggp_weather_scatterplot = 
  weather_df |> 
    ggplot(aes(x = tmin, y = tmax)) + 
    geom_point()

ggp_weather_scatterplot
```

check that some rows are missing
```{r}
weather_df |>
  filter(is.na(tmax))
```

# Fancier Scatterplot
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  geom_smooth(se = FALSE)
```

where you define aesthetics can matter
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.3, size = 0.6) + 
  geom_smooth(se = FALSE)

```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name, size = prcp), alpha = 0.3) + 
  geom_smooth(se = FALSE)
```

use faceting real quick
```{r}

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) + 
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

```

```{r}

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) + 
  geom_smooth(se = FALSE) +
  facet_grid(name ~ .)

```

let's make a somewhat more interesting scatterplot

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = 0.3) + 
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name) 
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(aes(size = prcp), alpha = 0.3) + 
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name) 
```

LA plot:  
```{r}
weather_df |>
  filter(name == "CentrolPark_NY") |>
  mutate(
    tmax_fahr = tmax * (9/5) + 32,
    tmin_fahr = tmin * (9/5) + 32
  ) |>
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) + 
    geom_point() +
    geom_smooth(se = FALSE, method = "lm")
    
  
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  #geom_point(aes(size = prcp), alpha = 0.3) + 
  geom_smooth(se = FALSE)

weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_smooth(se = FALSE)+
  geom_point()
  
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(color = "purple")
 
```

# univariate plots
```{r}
weather_df |>
  ggplot(aes(x = tmin)) + 
  geom_histogram(color = "white", fill = "red")
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, color = name)) + 
  geom_histogram()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) + 
  geom_histogram()+
  facet_grid(name ~ .)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, color = name)) + 
  geom_density()
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, fill = name)) + 
  geom_density(alpha = 0.2)
```

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin)) + 
  geom_boxplot(aes(fill = name))
```

violin plot
```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin)) + 
  geom_violin()
```

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmin, fill = name)) + 
  geom_violin()
```

ridge plot
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = name)) +
  geom_density_ridges()
```

```{r}
weather_df |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.2)

weather_df |>
  ggplot(aes(x = prcp, fill = name)) +
  geom_histogram()+
  facet_grid(name~.)

weather_df |>
  filter(prcp > 5, prcp<1000)|>
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.2)
```

saving plots
```{r}
ggp_weather_violin = 
weather_df |>
  ggplot(aes(x = name, y = tmin)) + 
  geom_violin()

ggp_weather_violin

ggsave("plots/violin_plot.pdf", ggp_weather_violin,
       width = 8, height = 6)
```

embedding plots
```{r, fig.width=6, fig.height=4}
ggp_weather_violin

```

