---
title: "Data Import"
output: github_document
---


```{r}
library(tidyverse)
library(readxl)
library(haven)
```

let's import a dataset.

```{r}
litters_df=
  read_csv("data_import_examples/FAS_litters.csv")
```

```{r}
names(litters_df)
```

upload the names in 'litters_df'.

```{r}
litters_df = 
  janitor::clean_names(litters_df)
```

look at the data

```{r}
litters_df
```

sometimes skimming data is neat?
```{r}
skimr::skim(litters_df)
```

#Fix the missingness
```{r}
litters_df = 
  read_csv("data_import_examples/FAS_litters.csv", na = c("NA", ".", ""), skip = 5)
```

#import PUPS data
```{r}
pups_df = 
  read_csv(
    "data_import_examples/FAS_pups.csv",
    na = c("NA", ".", ""), 
    skip = 3,
    )
pups_df = 
  janitor::clean_names(pups_df)
```


# About excel
CSVs are really great but sometimes you get an excel file.

```{r}
mlb_df = 
  read_excel("data_import_examples/mlb11.xlsx")
```

Import LotR word counts
```{r}
fotr_df = 
  read_excel("data_import_examples/LotR_Words.xlsx", range = "B3:D6")
```

# SAS
```{r}
Pulse_df = 
  read_sas("data_import_examples/public_pulse_data.sas7bdat")

Pulse_df = 
  janitor::clean_names(Pulse_df)
```


#why hate readcsv
```{r, eval=FALSE}
litters_df_base =
  read.csv("data_import_examples/FAS_litters.csv")
```

#what about data exporting
```{r}
write_csv(fotr_df, "data_import_examples/fort_df.csv")
```



